version: "3.9"

name: dev-gateway

networks:
  edge:
    external: true
  mesh:
    external: true

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: dev-gateway
    ports:
      - "80:80"            # browser hits http://localhost
      # - "443:443"        # enable if you add TLS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - edge               # public side (browser <-> gateway)
      - mesh               # private side (gateway <-> services)
    restart: unless-stopped
