"""add price

Revision ID: b9665ba78a88
Revises: d509fd4fcc0a
Create Date: 2025-09-05 17:13:36.063588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9665ba78a88'
down_revision: Union[str, None] = 'd509fd4fcc0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('product_variants', sa.Column('compare_at', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'compare_at')
    op.drop_column('product_variants', 'price')
    # ### end Alembic commands ###
